In [22]:
import numpy as np

In [24]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [35]:
arr = np.arange(1,11)

In [36]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
bool_arr = arr > 5

In [40]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [41]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [42]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [43]:
arr[arr<3]

array([1, 2])

In [44]:
arr_2d = np.arange(50).reshape(5,10)

In [48]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [47]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])